//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.RoboticsTutorial1.Y2006.M06, Version=0.0.0.0, Culture=neutral, PublicKeyToke" +
    "n=7f9074033fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial1.Proxy.RoboticsTutorial1State), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial1_Proxy_RoboticsTutorial1State_TO_Microsoft_Robotics_Services_RoboticsTutorial1_RoboticsTutorial1State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial1.RoboticsTutorial1State), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial1_RoboticsTutorial1State_TO_Microsoft_Robotics_Services_RoboticsTutorial1_Proxy_RoboticsTutorial1State));
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial1.Proxy.RoboticsTutorial1State _cachedInstance0 = new global::Microsoft.Robotics.Services.RoboticsTutorial1.Proxy.RoboticsTutorial1State();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial1.RoboticsTutorial1State _cachedInstance = new global::Microsoft.Robotics.Services.RoboticsTutorial1.RoboticsTutorial1State();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial1_Proxy_RoboticsTutorial1State_TO_Microsoft_Robotics_Services_RoboticsTutorial1_RoboticsTutorial1State(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial1_RoboticsTutorial1State_TO_Microsoft_Robotics_Services_RoboticsTutorial1_Proxy_RoboticsTutorial1State(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
