//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.KinectUI.Y2008.M08, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7f90740" +
    "33fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Dss.Services.Samples.KinectUI.Proxy.KinectUIState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Dss_Services_Samples_KinectUI_Proxy_KinectUIState_TO_Microsoft_Dss_Services_Samples_KinectUI_KinectUIState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Dss.Services.Samples.KinectUI.KinectUIState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Dss_Services_Samples_KinectUI_KinectUIState_TO_Microsoft_Dss_Services_Samples_KinectUI_Proxy_KinectUIState));
        }
        
        private static global::Microsoft.Dss.Services.Samples.KinectUI.Proxy.KinectUIState _cachedInstance0 = new global::Microsoft.Dss.Services.Samples.KinectUI.Proxy.KinectUIState();
        
        private static global::Microsoft.Dss.Services.Samples.KinectUI.KinectUIState _cachedInstance = new global::Microsoft.Dss.Services.Samples.KinectUI.KinectUIState();
        
        public static object Microsoft_Dss_Services_Samples_KinectUI_Proxy_KinectUIState_TO_Microsoft_Dss_Services_Samples_KinectUI_KinectUIState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Microsoft_Dss_Services_Samples_KinectUI_KinectUIState_TO_Microsoft_Dss_Services_Samples_KinectUI_Proxy_KinectUIState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
