//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.MicArraySpeechRecognizerGui.Y2011.M06, Version=0.0.0.0, Culture=neutral, Pub" +
    "licKeyToken=7f9074033fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerGuiState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerGuiState_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerGuiState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerGuiState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerGuiState_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerGuiState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryResponse_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryResponse_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerStateQueryRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerStateQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerStateQueryRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerStateQueryRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerStateQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerStateQueryRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.HttpPostSuccess), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_HttpPostSuccess_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_HttpPostSuccess));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.HttpPostSuccess), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_HttpPostSuccess_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_HttpPostSuccess));
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerGuiState_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerGuiState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerGuiState target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerGuiState();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerGuiState from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerGuiState)(transformFrom));
            if ((from.SpeechRecognizerState != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState tmp = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState();
                ((Microsoft.Dss.Core.IDssSerializable)(from.SpeechRecognizerState)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                target.SpeechRecognizerState = tmp;
            }
            else {
                target.SpeechRecognizerState = null;
            }
            if ((from.SpeechEvents != null)) {
                int count = from.SpeechEvents.Count;
                global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry> tmp0 = new global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry tmp1 = default(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry);
                    if ((from.SpeechEvents[index] != null)) {
                        tmp1 = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry)(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry(from.SpeechEvents[index])));
                    }
                    else {
                        tmp1 = null;
                    }
                    tmp0.Add(tmp1);
                }
                target.SpeechEvents = tmp0;
            }
            else {
                target.SpeechEvents = null;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerGuiState_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerGuiState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerGuiState target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerGuiState();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerGuiState from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerGuiState)(transformFrom));
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState tmp = from.SpeechRecognizerState;
            if ((tmp != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState tmp0 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                target.SpeechRecognizerState = tmp0;
            }
            global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry> tmp1 = from.SpeechEvents;
            if ((tmp1 != null)) {
                int count = tmp1.Count;
                global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry> tmp2 = new global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry tmp3 = default(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry);
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry tmp4 = tmp1[index];
                    if ((tmp4 != null)) {
                        tmp3 = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry)(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry(tmp4)));
                    }
                    tmp2.Add(tmp3);
                }
                target.SpeechEvents = tmp2;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry)(transformFrom));
            target.Timestamp = from.Timestamp;
            if ((from.SpeechDetected != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification tmp = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(from.SpeechDetected)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                target.SpeechDetected = tmp;
            }
            else {
                target.SpeechDetected = null;
            }
            if ((from.SpeechRecognized != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification tmp0 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(from.SpeechRecognized)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                target.SpeechRecognized = tmp0;
            }
            else {
                target.SpeechRecognized = null;
            }
            if ((from.RecognitionRejected != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification tmp1 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(from.RecognitionRejected)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp1)));
                target.RecognitionRejected = tmp1;
            }
            else {
                target.RecognitionRejected = null;
            }
            if ((from.BeamDirectionChanged != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification tmp2 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(from.BeamDirectionChanged)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                target.BeamDirectionChanged = tmp2;
            }
            else {
                target.BeamDirectionChanged = null;
            }
            if ((from.SpeechInformation != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation tmp3 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation();
                ((Microsoft.Dss.Core.IDssSerializable)(from.SpeechInformation)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp3)));
                target.SpeechInformation = tmp3;
            }
            else {
                target.SpeechInformation = null;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry)(transformFrom));
            target.Timestamp = from.Timestamp;
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification tmp = from.SpeechDetected;
            if ((tmp != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification tmp0 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                target.SpeechDetected = tmp0;
            }
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification tmp1 = from.SpeechRecognized;
            if ((tmp1 != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification tmp2 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp1)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                target.SpeechRecognized = tmp2;
            }
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification tmp3 = from.RecognitionRejected;
            if ((tmp3 != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification tmp4 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp3)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp4)));
                target.RecognitionRejected = tmp4;
            }
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification tmp5 = from.BeamDirectionChanged;
            if ((tmp5 != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification tmp6 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp5)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp6)));
                target.BeamDirectionChanged = tmp6;
            }
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation tmp7 = from.SpeechInformation;
            if ((tmp7 != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation tmp8 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp7)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp8)));
                target.SpeechInformation = tmp8;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryRequestType(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryRequestType target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryRequestType();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryRequestType from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryRequestType)(transformFrom));
            target.NewerThanTimestamp = from.NewerThanTimestamp;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryRequestType(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryRequestType target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryRequestType();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryRequestType from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryRequestType)(transformFrom));
            target.NewerThanTimestamp = from.NewerThanTimestamp;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryResponse_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryResponse(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryResponse target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryResponse();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryResponse from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryResponse)(transformFrom));
            if ((from.Events != null)) {
                int count = from.Events.Count;
                global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry> tmp = new global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry tmp0 = default(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry);
                    if ((from.Events[index] != null)) {
                        tmp0 = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry)(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry(from.Events[index])));
                    }
                    else {
                        tmp0 = null;
                    }
                    tmp.Add(tmp0);
                }
                target.Events = tmp;
            }
            else {
                target.Events = null;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventsQueryResponse_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventsQueryResponse(object transformFrom) {
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryResponse target = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventsQueryResponse();
            global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryResponse from = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventsQueryResponse)(transformFrom));
            global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry> tmp = from.Events;
            if ((tmp != null)) {
                int count = tmp.Count;
                global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry> tmp0 = new global::System.Collections.Generic.List<global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry tmp1 = default(global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry);
                    global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.EventListEntry tmp2 = tmp[index];
                    if ((tmp2 != null)) {
                        tmp1 = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.EventListEntry)(Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_EventListEntry_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_EventListEntry(tmp2)));
                    }
                    tmp0.Add(tmp1);
                }
                target.Events = tmp0;
            }
            return target;
        }
        
        private static global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerStateQueryRequestType _cachedInstance0 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.SpeechRecognizerStateQueryRequestType();
        
        private static global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerStateQueryRequestType _cachedInstance = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.SpeechRecognizerStateQueryRequestType();
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerStateQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerStateQueryRequestType(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_SpeechRecognizerStateQueryRequestType_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_SpeechRecognizerStateQueryRequestType(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.HttpPostSuccess _cachedInstance2 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.Proxy.HttpPostSuccess();
        
        private static global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.HttpPostSuccess _cachedInstance1 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizerGui.HttpPostSuccess();
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_HttpPostSuccess_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_HttpPostSuccess(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_HttpPostSuccess_TO_Microsoft_Robotics_Services_Sensors_Kinect_MicArraySpeechRecognizerGui_Proxy_HttpPostSuccess(object transformFrom) {
            return _cachedInstance2;
        }
    }
}
