//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="DriveByVoice.Y2013.M09, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7f907403" +
    "3fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformDriveByVoice {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.DriveByVoice.Diagram.Proxy.ActionRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_Proxy_ActionRequest_TO_Robotics_DriveByVoice_Diagram_ActionRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.DriveByVoice.Diagram.ActionRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_ActionRequest_TO_Robotics_DriveByVoice_Diagram_Proxy_ActionRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.DriveByVoice.Diagram.Proxy.ActionResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_Proxy_ActionResponse_TO_Robotics_DriveByVoice_Diagram_ActionResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.DriveByVoice.Diagram.ActionResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_ActionResponse_TO_Robotics_DriveByVoice_Diagram_Proxy_ActionResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.DriveByVoice.Diagram.Proxy.DiagramState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_Proxy_DiagramState_TO_Robotics_DriveByVoice_Diagram_DiagramState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.DriveByVoice.Diagram.DiagramState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_DriveByVoice_Diagram_DiagramState_TO_Robotics_DriveByVoice_Diagram_Proxy_DiagramState));
        }
        
        private static global::Robotics.DriveByVoice.Diagram.Proxy.ActionRequest _cachedInstance0 = new global::Robotics.DriveByVoice.Diagram.Proxy.ActionRequest();
        
        private static global::Robotics.DriveByVoice.Diagram.ActionRequest _cachedInstance = new global::Robotics.DriveByVoice.Diagram.ActionRequest();
        
        public static object Robotics_DriveByVoice_Diagram_Proxy_ActionRequest_TO_Robotics_DriveByVoice_Diagram_ActionRequest(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Robotics_DriveByVoice_Diagram_ActionRequest_TO_Robotics_DriveByVoice_Diagram_Proxy_ActionRequest(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Robotics.DriveByVoice.Diagram.Proxy.ActionResponse _cachedInstance2 = new global::Robotics.DriveByVoice.Diagram.Proxy.ActionResponse();
        
        private static global::Robotics.DriveByVoice.Diagram.ActionResponse _cachedInstance1 = new global::Robotics.DriveByVoice.Diagram.ActionResponse();
        
        public static object Robotics_DriveByVoice_Diagram_Proxy_ActionResponse_TO_Robotics_DriveByVoice_Diagram_ActionResponse(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Robotics_DriveByVoice_Diagram_ActionResponse_TO_Robotics_DriveByVoice_Diagram_Proxy_ActionResponse(object transformFrom) {
            return _cachedInstance2;
        }
        
        public static object Robotics_DriveByVoice_Diagram_Proxy_DiagramState_TO_Robotics_DriveByVoice_Diagram_DiagramState(object transformFrom) {
            global::Robotics.DriveByVoice.Diagram.DiagramState target = new global::Robotics.DriveByVoice.Diagram.DiagramState();
            global::Robotics.DriveByVoice.Diagram.Proxy.DiagramState from = ((global::Robotics.DriveByVoice.Diagram.Proxy.DiagramState)(transformFrom));
            target.LeftSpeed = from.LeftSpeed;
            target.RighSpeed = from.RighSpeed;
            return target;
        }
        
        public static object Robotics_DriveByVoice_Diagram_DiagramState_TO_Robotics_DriveByVoice_Diagram_Proxy_DiagramState(object transformFrom) {
            global::Robotics.DriveByVoice.Diagram.Proxy.DiagramState target = new global::Robotics.DriveByVoice.Diagram.Proxy.DiagramState();
            global::Robotics.DriveByVoice.Diagram.DiagramState from = ((global::Robotics.DriveByVoice.Diagram.DiagramState)(transformFrom));
            target.LeftSpeed = from.LeftSpeed;
            target.RighSpeed = from.RighSpeed;
            return target;
        }
    }
}
