//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.ServiceTutorial10.Y2007.M12, Version=0.0.0.0, Culture=neutral, PublicKeyToke" +
    "n=7f9074033fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::ServiceTutorial10.Proxy.ServiceTutorial10State), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial10_Proxy_ServiceTutorial10State_TO_ServiceTutorial10_ServiceTutorial10State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::ServiceTutorial10.ServiceTutorial10State), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial10_ServiceTutorial10State_TO_ServiceTutorial10_Proxy_ServiceTutorial10State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::ServiceTutorial10.Proxy.TutorialCategories), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial10_Proxy_TutorialCategories_TO_ServiceTutorial10_TutorialCategories));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::ServiceTutorial10.TutorialCategories), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial10_TutorialCategories_TO_ServiceTutorial10_Proxy_TutorialCategories));
        }
        
        public static object ServiceTutorial10_Proxy_ServiceTutorial10State_TO_ServiceTutorial10_ServiceTutorial10State(object transformFrom) {
            global::ServiceTutorial10.ServiceTutorial10State target = new global::ServiceTutorial10.ServiceTutorial10State();
            global::ServiceTutorial10.Proxy.ServiceTutorial10State from = ((global::ServiceTutorial10.Proxy.ServiceTutorial10State)(transformFrom));
            target.FirstName = from.FirstName;
            target.Initials = from.Initials;
            target.LastName = from.LastName;
            target.LastModified = from.LastModified;
            return target;
        }
        
        public static object ServiceTutorial10_ServiceTutorial10State_TO_ServiceTutorial10_Proxy_ServiceTutorial10State(object transformFrom) {
            global::ServiceTutorial10.Proxy.ServiceTutorial10State target = new global::ServiceTutorial10.Proxy.ServiceTutorial10State();
            global::ServiceTutorial10.ServiceTutorial10State from = ((global::ServiceTutorial10.ServiceTutorial10State)(transformFrom));
            target.FirstName = from.FirstName;
            target.Initials = from.Initials;
            target.LastName = from.LastName;
            target.LastModified = from.LastModified;
            return target;
        }
        
        private static global::ServiceTutorial10.Proxy.TutorialCategories _cachedInstance0 = new global::ServiceTutorial10.Proxy.TutorialCategories();
        
        private static global::ServiceTutorial10.TutorialCategories _cachedInstance = new global::ServiceTutorial10.TutorialCategories();
        
        public static object ServiceTutorial10_Proxy_TutorialCategories_TO_ServiceTutorial10_TutorialCategories(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object ServiceTutorial10_TutorialCategories_TO_ServiceTutorial10_Proxy_TutorialCategories(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
