//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.ServiceTutorial9.Y2006.M06, Version=0.0.0.0, Culture=neutral, PublicKeyToken" +
    "=7f9074033fd3dcf7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::ServiceTutorial9.Multi.Proxy.AddressState), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Multi_Proxy_AddressState_TO_ServiceTutorial9_Multi_AddressState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::ServiceTutorial9.Multi.AddressState), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Multi_AddressState_TO_ServiceTutorial9_Multi_Proxy_AddressState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::ServiceTutorial9.Extension.Proxy.ExtensionState), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Extension_Proxy_ExtensionState_TO_ServiceTutorial9_Extension_ExtensionState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::ServiceTutorial9.Extension.ExtensionState), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Extension_ExtensionState_TO_ServiceTutorial9_Extension_Proxy_ExtensionState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::ServiceTutorial9.Extension.Proxy.UpdateAgeRequest), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Extension_Proxy_UpdateAgeRequest_TO_ServiceTutorial9_Extension_UpdateAgeRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::ServiceTutorial9.Extension.UpdateAgeRequest), new global::Microsoft.Dss.Core.Attributes.Transform(ServiceTutorial9_Extension_UpdateAgeRequest_TO_ServiceTutorial9_Extension_Proxy_UpdateAgeRequest));
        }
        
        public static object ServiceTutorial9_Multi_Proxy_AddressState_TO_ServiceTutorial9_Multi_AddressState(object transformFrom) {
            global::ServiceTutorial9.Multi.AddressState target = new global::ServiceTutorial9.Multi.AddressState();
            global::ServiceTutorial9.Multi.Proxy.AddressState from = ((global::ServiceTutorial9.Multi.Proxy.AddressState)(transformFrom));
            target.Address = from.Address;
            target.ZipCode = from.ZipCode;
            return target;
        }
        
        public static object ServiceTutorial9_Multi_AddressState_TO_ServiceTutorial9_Multi_Proxy_AddressState(object transformFrom) {
            global::ServiceTutorial9.Multi.Proxy.AddressState target = new global::ServiceTutorial9.Multi.Proxy.AddressState();
            global::ServiceTutorial9.Multi.AddressState from = ((global::ServiceTutorial9.Multi.AddressState)(transformFrom));
            target.Address = from.Address;
            target.ZipCode = from.ZipCode;
            return target;
        }
        
        public static object ServiceTutorial9_Extension_Proxy_ExtensionState_TO_ServiceTutorial9_Extension_ExtensionState(object transformFrom) {
            global::ServiceTutorial9.Extension.ExtensionState target = new global::ServiceTutorial9.Extension.ExtensionState();
            global::ServiceTutorial9.Extension.Proxy.ExtensionState from = ((global::ServiceTutorial9.Extension.Proxy.ExtensionState)(transformFrom));
            target.Age = from.Age;
            target.FirstName = from.FirstName;
            target.LastName = from.LastName;
            return target;
        }
        
        public static object ServiceTutorial9_Extension_ExtensionState_TO_ServiceTutorial9_Extension_Proxy_ExtensionState(object transformFrom) {
            global::ServiceTutorial9.Extension.Proxy.ExtensionState target = new global::ServiceTutorial9.Extension.Proxy.ExtensionState();
            global::ServiceTutorial9.Extension.ExtensionState from = ((global::ServiceTutorial9.Extension.ExtensionState)(transformFrom));
            target.Age = from.Age;
            target.FirstName = from.FirstName;
            target.LastName = from.LastName;
            return target;
        }
        
        public static object ServiceTutorial9_Extension_Proxy_UpdateAgeRequest_TO_ServiceTutorial9_Extension_UpdateAgeRequest(object transformFrom) {
            global::ServiceTutorial9.Extension.UpdateAgeRequest target = new global::ServiceTutorial9.Extension.UpdateAgeRequest();
            global::ServiceTutorial9.Extension.Proxy.UpdateAgeRequest from = ((global::ServiceTutorial9.Extension.Proxy.UpdateAgeRequest)(transformFrom));
            target.Age = from.Age;
            return target;
        }
        
        public static object ServiceTutorial9_Extension_UpdateAgeRequest_TO_ServiceTutorial9_Extension_Proxy_UpdateAgeRequest(object transformFrom) {
            global::ServiceTutorial9.Extension.Proxy.UpdateAgeRequest target = new global::ServiceTutorial9.Extension.Proxy.UpdateAgeRequest();
            global::ServiceTutorial9.Extension.UpdateAgeRequest from = ((global::ServiceTutorial9.Extension.UpdateAgeRequest)(transformFrom));
            target.Age = from.Age;
            return target;
        }
    }
}
